Repository ALOC-UOS/aloc-backend-v1, pull requests merged in 2024-06, with the labels that each got.

#7 feat: add checkstyle
  .DS_Store
  .editorconfig
  build.gradle
  config/naver-checkstyle-rules.xml
  config/naver-checkstyle-suppressions.xml
  src/.DS_Store
  src/main/java/com/aloc/aloc/common/domain/AuditingTimeEntity.java
  src/main/java/com/aloc/aloc/controller/UserController.java
  src/main/java/com/aloc/aloc/domain/Problem.java
  src/main/java/com/aloc/aloc/domain/SolvedProblem.java
  src/main/java/com/aloc/aloc/domain/User.java
  src/main/java/com/aloc/aloc/repository/UserRepository.java
Labels: ⚙️ Setting, ✨ Feature

#9 feat: security config
  build.gradle
  src/main/java/com/aloc/aloc/controller/UserController.java
  src/main/java/com/aloc/aloc/domain/User.java
  src/main/java/com/aloc/aloc/domain/algorithm/Algorithm.java
  src/main/java/com/aloc/aloc/domain/color/Color.java
  src/main/java/com/aloc/aloc/domain/history/History.java
  src/main/java/com/aloc/aloc/domain/problem/Problem.java
  src/main/java/com/aloc/aloc/domain/solvedproblem/SolvedProblem.java
  src/main/java/com/aloc/aloc/domain/user/User.java
  src/main/java/com/aloc/aloc/domain/user/controller/UserController.java
  src/main/java/com/aloc/aloc/domain/user/dto/request/UserRequestDto.java
  src/main/java/com/aloc/aloc/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/aloc/aloc/domain/user/enums/Authority.java
  src/main/java/com/aloc/aloc/domain/user/repository/UserRepository.java
  src/main/java/com/aloc/aloc/domain/user/service/LoginService.java
  src/main/java/com/aloc/aloc/domain/user/service/UserService.java
  src/main/java/com/aloc/aloc/global/config/SecurityConfig.java
  src/main/java/com/aloc/aloc/global/domain/AuditingTimeEntity.java
  src/main/java/com/aloc/aloc/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/aloc/aloc/global/jwt/service/JwtService.java
  src/main/java/com/aloc/aloc/global/jwt/service/JwtServiceImpl.java
  src/main/java/com/aloc/aloc/global/login/filter/JsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/aloc/aloc/global/login/handler/JwtProviderHandler.java
  src/main/java/com/aloc/aloc/global/login/handler/LoginFailureHandler.java
  src/main/java/com/aloc/aloc/global/login/service/CustomeUserDetailsService.java
  src/main/java/com/aloc/aloc/global/login/service/UserDetailsServiceImpl.java
  src/main/java/com/aloc/aloc/repository/UserRepository.java
  src/main/resources/application.properties
  src/test/java/com/aloc/aloc/global/jwt/filter/JwtFilterAuthenticationTest.java
  src/test/java/com/aloc/aloc/global/jwt/service/JwtServiceTest.java
Labels: ⚙️ Setting, ✨ Feature, ✅ Test

#12 feat: add Dockerfile
  Dockerfile
  docker-compose.yml
  src/main/java/com/aloc/aloc/global/config/SwaggerConfig.java
  src/main/java/com/aloc/aloc/global/login/filter/JsonUsernamePasswordAuthenticationFilter.java
Labels: ⚙️ Setting

#18 fix: change sign up dto
  build.gradle
  src/main/java/com/aloc/aloc/domain/user/User.java
  src/main/java/com/aloc/aloc/domain/user/dto/request/UserRequestDto.java
  src/test/java/com/aloc/aloc/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/aloc/aloc/domain/auth/service/AuthServiceTest.java
  src/test/java/com/aloc/aloc/global/jwt/filter/JwtFilterAuthenticationTest.java
  src/test/java/com/aloc/aloc/global/jwt/service/JwtServiceTest.java
Labels: ✨ Feature
